#配置视图解析器和数据库
spring:
  mvc:
    view:
      prefix: /jsps/
      suffix: .jsp
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://192.168.32.169:3306/wx_yiyuan?&allowMultiQueries=true&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  data:
    solr:
      host: http://localhost:8983/solr/coreName1
  redis:
    database: 0
    host: localhost
    port: 6379
    pool:
    # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    # 连接池中的最大空闲连接
      max-idle: 10
    # 连接池中的最小空闲连接
      min-idle: 0
    timeout: 1000
#配置热部署
server:
  port: 8088
  jsp-servlet:
    init-parameters:
      development: true
#配置mybatis 扫描mapper配置文件   其别名  开启驼峰命名
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qianquan.guoda.pojo
  configuration:
    map-underscore-to-camel-case: true
#打印sql语句
logging:
  level:
    com.qianquan.guoda.mapper: debug
pagehelper:
  reasonable: true
  helper-dialect: mysql

User:
  path: D://ideaWorkspace/追云2/guodaFile
  pathname: /home/ftpuser

#ueditor文件上传路径的设置
web:
  upload-path: D://ideaWorkspace/1803A/beichencarFile/goodsDetailImg/

aliyun-oss:
#bucket名称
  bucketName: xhwy
  endpoint : https://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4FrWMhChuKKB1w2eiVyo
  accessKeySecret: x3rI7gN6sKCBc4LtiCli2iYp2VTdN5
  fileHost: guoda